### PR TITLE
Fix panic in `pallet-collator-selection` benchmarking

### LINKED ISSUE #1062: Panic when benchmarking `pallet-collator-selection`
Steps to reproduce the error:
1. check out the master branch or `polkadot-v0.9.17`
2. `cargo build --features=runtime-benchmarks --release`
3. `./target/release/parachain-collator benchmark --execution=wasm --db-cache=20 --pallet=pallet-collator-selection --extrinsic=* --steps=20 --repeat=50`

The error comes from the change since `polkadot-v0.9.17` where `set_invulnerables()` requires the new validator keys [to be registered](https://github.com/Kailai-Wang/cumulus/blob/master/pallets/collator-selection/src/lib.rs#L305-L306).

I also have a [PR](https://github.com/paritytech/cumulus/pull/1061) trying to solve this, please let me know if it's appropriate.

### PR DESCRIPTION
**Pull request by Kailai-Wang**
resolves #1062 

This PR tries to fix the error by returning validator accounts in `register_validators` and using them in the `set_invulnerables` benchmarking.

### CODE REVIEW

File: pallets/collator-selection/src/benchmarking.rs [hunk 1]
```diff
@@ -84,12 +84,14 @@ fn validator<T: Config + session::Config>(c: u32) -> (T::AccountId, <T as sessio
...
-fn register_validators<T: Config + session::Config>(count: u32) {
+fn register_validators<T: Config + session::Config>(count: u32) -> Vec<T::AccountId> {
 	let validators = (0..count).map(|c| validator::<T>(c)).collect::<Vec<_>>();
 
-	for (who, keys) in validators {
+	for (who, keys) in validators.clone() {
 		<session::Pallet<T>>::set_keys(RawOrigin::Signed(who).into(), keys, Vec::new()).unwrap();
 	}
+
+	return validators.into_iter().map(|(who, _)| who).collect()
```
Comment (bkchr) [inline pallets/collator-selection/src/benchmarking.rs:94]:
```suggestion
	validators.into_iter().map(|(who, _)| who).collect()
```

File: pallets/collator-selection/src/benchmarking.rs [hunk 2]
```diff
@@ -150,7 +152,7 @@ benchmarks! {
 		<CandidacyBond<T>>::put(T::Currency::minimum_balance());
 		<DesiredCandidates<T>>::put(c + 1);
 
-		register_validators::<T>(c);
+		let _ = register_validators::<T>(c);
```
Comment (bkchr) [inline pallets/collator-selection/src/benchmarking.rs:155]:
```suggestion
		register_validators::<T>(c);
```

File: pallets/collator-selection/src/benchmarking.rs [hunk 3]
```diff
@@ -174,7 +176,7 @@ benchmarks! {
 		<CandidacyBond<T>>::put(T::Currency::minimum_balance());
 		<DesiredCandidates<T>>::put(c);
 
-		register_validators::<T>(c);
+		let _ = register_validators::<T>(c);
```
Comment (bkchr) [inline pallets/collator-selection/src/benchmarking.rs:179]:
```suggestion
		register_validators::<T>(c);
```

File: pallets/collator-selection/src/benchmarking.rs [hunk 4]
```diff
@@ -212,7 +214,7 @@ benchmarks! {
 		<DesiredCandidates<T>>::put(c);
 		frame_system::Pallet::<T>::set_block_number(0u32.into());
 
-		register_validators::<T>(c);
+		let _ = register_validators::<T>(c);
```
Comment (bkchr) [inline pallets/collator-selection/src/benchmarking.rs:217]:
```suggestion
		register_validators::<T>(c);
```

**Review by bkchr — APPROVED** [review]

**Comment by seunlanlege** [comment]
possible to cherry pick this commit into the `release-v0.9.17` branch?
